package webui

import (
	"net/http"

	"github.com/sn0wfree/llmRx/internal/model"
)

// formErrorView centralizes the boilerplate every form handler used
// to repeat: (1) build a FormData map from r.Form, (2) call
// renderer.Render with the right body template, (3) handle the
// renderer error.
//
// Before this helper existed, every form (channels / tokens / combos /
// plans / alerts / users / config) had its own renderXxxFormError
// function with the same shape but different field lists. Adding a
// new field required touching 3-4 places; forgetting one would
// silently lose the user's input on validation errors.
//
// formErrorView takes the page-level "extra" data (Channel, Token,
// Plan, etc.) plus an explicit field-list describing which form keys
// to echo back. The caller writes the per-field error message into
// FieldErrors if it has field-level validation; otherwise it can
// leave the map nil and only FormError is shown.
//
// Usage:
//
//	if err := h.store.CreateChannel(ch); err != nil {
//	    h.renderFormError(w, r, &formErrorView{
//	        Body: "channels_form_body", Title: "新建通道",
//	        Active: "channels", Record: ch, Msg: "创建失败: "+err.Error(),
//	        Form: r.Form,
//	        Fields: []string{"name","provider","base_url","models","intents",
//	                          "priority","input_price","output_price","status"},
//	        Extras: map[string]any{"Providers": provider.AllProviders()},
//	    })
//	    return
//	}
type formErrorView struct {
	Body   string
	Title  string
	Active string

	Record any // *model.Channel / *model.Token / *model.Plan / *model.User / nil

	Msg  string
	Form map[string][]string

	// Fields is the ordered list of form input names that should be
	// echoed back so the user doesn't have to re-type everything on
	// a validation failure. The renderXxx field map keys are
	// generated by uppercasing the first letter of each entry
	// ("name" → "Name", "input_price" → "InputPrice"). For compound
	// names that don't follow that convention (e.g. "models" →
	// "ModelsStr"), provide the explicit mapping via FieldRenames.
	Fields []string

	// FieldRenames lets a field with a non-conventional FormData key
	// be aliased, e.g. {"models": "ModelsStr"}. Lookups first try
	// the renamed key, then fall back to TitleCase(field).
	FieldRenames map[string]string

	// FieldErrors provides per-field error text (e.g. "name": "不能为空").
	// When non-empty, the template can highlight that field with a
	// red border.
	FieldErrors map[string]string

	// Extras is forwarded verbatim into the page render data so
	// callers can attach providers list, NewKey, etc.
	Extras map[string]any
}

// renderFormError executes the unified error render path. It is
// shared by every form handler so the user sees consistent error
// UI and the dev sees one place to add new form fields.
func (h *Handler) renderFormError(w http.ResponseWriter, r *http.Request, v formErrorView) {
	fd := map[string]string{}
	for _, f := range v.Fields {
		if v.Form == nil {
			break
		}
		key := titleCase(f)
		if rename, ok := v.FieldRenames[f]; ok {
			key = rename
		}
		if s, ok := v.Form[f]; ok && len(s) > 0 {
			fd[key] = s[0]
		}
	}

	data := map[string]any{
		"Body":        v.Body,
		"Title":       v.Title,
		"User":        userToView(getUser(r)),
		"Active":      v.Active,
		"FormError":   v.Msg,
		"FormData":    fd,
		"FieldErrors": v.FieldErrors,
	}
	if v.Record != nil {
		data[recordKey(v.Record)] = v.Record
	}
	for k, val := range v.Extras {
		data[k] = val
	}

	if err := h.renderer.Render(w, v.Body, data); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

// recordKey maps a typed record to the data-map key the template
// expects. Centralized so the templates and handlers stay in sync.
func recordKey(rec any) string {
	switch rec.(type) {
	case *model.Channel:
		return "Channel"
	case *model.Token:
		return "Token"
	case *model.Plan:
		return "Plan"
	case *model.User:
		return "User"
	case *model.Alert:
		return "Alert"
	case *model.ProviderDef:
		return "ProviderDef"
	case *model.TokenComboModel:
		return "Combo"
	}
	return "Record"
}

// titleCase converts snake_case to CamelCase: "name" → "Name",
// "input_price" → "InputPrice", "base_url" → "BaseURL".
// Single-word inputs only get the first letter uppercased.
func titleCase(s string) string {
	if s == "" {
		return s
	}
	var b []byte
	upper := true
	for i := 0; i < len(s); i++ {
		c := s[i]
		if c == '_' {
			upper = true
			continue
		}
		if upper {
			if c >= 'a' && c <= 'z' {
				c -= 'a' - 'A'
			}
			upper = false
		}
		b = append(b, c)
	}
	return string(b)
}
